name: Golang Linting Workflow

on:
  # Trigger the workflow on push and pull requests
  push:
    branches: [ main]
  pull_request:
    branches: [ main]

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: false

    # Install and run golangci-lint
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v4
      with:
        version: latest
        args: --timeout=5m
        skip-cache: true

    # Run go vet for basic code analysis
    - name: Run go vet
      run: go vet ./...

    # Run go fmt to check formatting
    - name: Check formatting
      run: |
        if [ -n "$(go fmt ./...)" ]; then
          echo "Go fmt found formatting issues"
          exit 1
        fi

    # Static analysis with staticcheck
    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Run staticcheck
      run: staticcheck ./...

    # Security vulnerability scanning
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...

    # Dependency vulnerability check
    - name: Run nancy for dependency vulnerabilities
      uses: sonatype-nexus-community/nancy-github-action@main